### ISSUE TITLE
invalid positions and possibly suboptimal mate

### ISSUE THREAD

**Issue by robertnurnberg** [vondele/matetrack#6]
The file `ChestUCI_23102018.epd` contains five positions which cannot be reached from the standard starting position, and are hence treated as illegal by some engines/databases: most notably [chessdb.cn](https://chessdb.cn/queryc_en/). The positions are:
```
4k3/b7/1p1p4/pPpPp1p1/P1P1PpPp/5P1P/2QQ4/K7 w - -
Nb1QN3/1pp1PPp1/1rnn1p1P/1Pkr2B1/P1pRpK1p/2P1P2B/2qb2Pp/4R3 b - -
Nb1QN3/1pp1PPp1/1rnn1p1P/1Pkr2B1/P1pRpK1p/2P1P2B/2qb2Pp/4R3 w - -
1Brb1B2/Pbn1r3/2pkP3/2p2P2/2Pb1P2/1P1KpP2/1p2P3/4R3 w - -
Bk6/1P2p1pp/RP1p3p/P7/2P5/4p3/4p1p1/4Kbrb w - -
```

Moreover, recent mate tracking on [cdbmatetrack](https://github.com/robertnurnberg/cdbmatetrack) has led to the discovery of a possibly better mate score for the position
```
2r5/1p6/1Nk1p1pn/QpPp1p1r/6p1/nN3b1q/3R4/2BR2K1 w - - bm #26; 00:53 @ C3/R0/K6/P2/X5;
```
According to @dav1312, the best mate is in fact #25, giving the line:
```
1.Nd4+ Kc7 2.Nxb5+ Kc6 3.Nd4+ Kc7 4.Nxe6+ Kc6 5.Qa4+ Nb5 6.Nd4+ Kc7 7.Nxb5+ Kd8 8.Rxd5+ Bxd5 9.Rxd5+ Ke8 10.Nd6+ Kf8 11.Nd7+ Kg8 12.Nf6+ Kh8 13.Nxh5 Qc3 14.Bd2 Qb2 15.Qf4 Qa1+ 16.Kg2 Nf7 17.Nxf7+ Kg8 18.Nh6+ Kh8 19.Rd7 b5 20.Qd6 Qa8+ 21.Kh2 g3+ 22.Nxg3 Qa1 23.Qxg6 Qh1+ 24.Kxh1 b4 25.Qg7#
```
I tried to confirm this with a local analysis with SF (running in scid with MultiPV 4, no TBs). At depth 44 it gave me #25 with this alternative mating line:
```
44 M25 1.Nd4+ Kc7 2.Nxb5+ Nxb5 3.Nxd5+ Kb8 4.Qa8+ Kxa8 5.Ra2+ Kb8 6.Bf4+ e5 7.Bxe5+ Nd6 8.Bxd6+ Rc7 9.Bxc7+ Kc8 10.Ra8+ Kd7 11.Rd8+ Kc6 12.Rd6+ Kb5 13.Rb1+ Ka4 14.Ra1+ Kb3 15.Rb6+ Kc2 16.Ra2+ Kd3 17.Nf4+ Ke3 18.Ra3+ Kd4 19.Ra4+ Kc3 20.Be5+ Kd2 21.Rb2+ Ke3 22.Rb3+ Kd2 23.Ra2+ Ke1 24.Nd3+ Kd1 25.Rb1#
```
But leaving the analysis running it changed it later on back to #26:
```
51 M26 1.Nd4+ Kc7 2.Nxe6+ Kc6 3.Nd4+ Kc7 4.Nxb5+ Nxb5 5.Nxd5+ Kb8 6.Qa8+ Kxa8 7.Ra2+ Kb8 8.Bf4+ Nd6 9.Bxd6+ Rc7 10.Bxc7+ Kc8 11.Ra8+ Kd7 12.Rd8+ Kc6 13.Rd6+ Kb5 14.Rb1+ Ka4 15.Ra1+ Kb3 16.Rb6+ Kc2 17.Ra2+ Kd3 18.Nf4+ Ke3 19.Ra3+ Kd4 20.Ra4+ Kc3 21.Be5+ Kd2 22.Rb2+ Ke3 23.Rb3+ Kd2 24.Ra2+ Ke1 25.Bc3+ Kd1 26.Rb1# 
...
55 M26 1.Nd4+ Kc7 2.Nxe6+ Kc6 3.Nd4+ Kc7 4.Nxb5+ Nxb5 5.Nxd5+ Kb8 6.Qa8+ Kxa8 7.Ra2+ Kb8 8.Bf4+ Nd6 9.Bxd6+ Rc7 10.Bxc7+ Kc8 11.Ra8+ Kd7 12.Rd8+ Kc6 13.Rd6+ Kb5 14.Rb1+ Ka4 15.Ra1+ Kb3 16.Rb6+ Kc2 17.Ra2+ Kd3 18.Nf4+ Ke3 19.Ra3+ Kd4 20.Ra4+ Kc3 21.Be5+ Kd2 22.Rb2+ Ke3 23.Rb3+ Kd2 24.Ra2+ Ke1 25.Rb1+ Bd1 26.Re2#
```
So I am not sure what is going on @dav1312. Is the mate you reported proven? My guess is that your line has overlooked a better move by black somewhere? In any case, out of curiosity: If the wrong best mate is confirmed, would this be a problem with the Chest mate finding engine, or a just a transmission error in the .epd file?

Once we have confirmed whether or not that the best mate for this position is #25, I am happy to open a PR to fix these two  issues. In that case, would we go with `ChestUCI_20230525.epd` to mark the date the new best mate was found, or do we break with this naming convention and keep a new file `ChestUCI_matetrack.epd` which will then be possibly changed in future? @vondele 

PS: Is the change from M25 to M26 by SF in Multi-PV mode normal?

**Comment by dav1312** [comment]
I'm actually not sure where did Vondele take the `ChestUCI_23102018.epd` from.
I managed to find 2 ChestUCI.epd files, one from 2014 and another one from 2018, the matetrack file seems to be a mix of both but with some positions removed, but not sure.

**Comment by robertnurnberg** [comment]
I managed to install `Chest`. Do you know the command line options I need for this EPD to make it report #26 or #25? @dav1312

**Comment by robertnurnberg** [comment]
I have given up on `Chest`, as it is too slow. Instead I have started `bench 4096 16 25 inputfile.epd mate` runs for both huntsman and stockfish. I know David thinks this is a waste of electricity, but I'd rather be 100% sure that this #25 is correct. So far these are the latest outputs for huntsman and stockfish, respectively:
```
info depth 56 seldepth 52 multipv 1 score mate 26 nodes 400117050038 nps 8326461 hashfull 1000 tbhits 0 time 48053671 pv b3d4 c6c7 d4e6 c7c6 e6d4 c6c7 d4b5 a3b5 b6d5 c7b8 a5a8 b8a8 d2a2 a8b8 c1f4 b5d6 f4d6 c8c7 d6c7 b8c8 a2a8 c8d7 a8d8 d7c6 d8d6 c6b5 d1b1 b5a4 b1a1 a4b3 d6b6 b3c2 a1a2 c2d3 d5f4 d3e3 a2a3 e3d4 a3a4 d4c3 c7e5 c3d2 b6b2 d2e3 b2b3 e3d2 a4a2 d2c1 f4d3 c1d1 b3b1
```
```
info depth 65 seldepth 52 multipv 1 score mate 26 nodes 267937759120 nps 10401156 hashfull 1000 tbhits 0 time 25760382 pv b3d4 c6c7 d4e6 c7c6 e6d4 c6c7 d4b5 a3b5 b6d5 c7b8 a5a8 b8a8 d2a2 a8b8 c1f4 b5d6 f4d6 c8c7 d6c7 b8c8 a2a8 c8d7 a8d8 d7c6 d8d6 c6b5 d1b1 b5a4 b1a1 a4b3 d6b6 b3c2 a1a2 c2d3 d5f4 d3e3 a2a3 e3d4 a3a4 d4c3 c7e5 c3d2 b6b2 d2e3 b2b3 e3d2 a4a2 d2c1 f4d3 c1d1 b3b1
```

Is there a depth by which sf must have found the mate in 25 if it exists?

**Comment by vondele** [comment]
no, there is no guarantee to find a mate in 25.

**Comment by robertnurnberg** [comment]
So what is your gut feeling regarding the mate in 25? @vondele Do you trust the two #25 lines given above? (I am not enough of a chess expert to verify these myself.)

Could the #25 mate announcements seen by David and myself in theory be incorrect due to some TT collision?

I think it would be nice if we could attach some logs of some engine to this issue, which show a clear mate #25 announcement and the steps to reproduce.

**Comment by vondele** [comment]
The idea is that if there is a mate announcement by SF, that announcement is correct (i.e. no better defense possible). That doesn't exclude bugs, but we haven't had bugs like that for a while. 

Having a #25 and later not finding it any longer (i.e. #26) can happen, especially in multiPV. Also the #25 is found by various people using different number of threads, hash sizes, and versions, so I think it is rather safe to assume it is correct.

**Comment by robertnurnberg** [comment]
> I have given up on `Chest`, as it is too slow. Instead I have started `bench 4096 16 25 inputfile.epd mate` runs for both huntsman and stockfish. I know David thinks this is a waste of electricity, but I'd rather be 100% sure that this #25 is correct. So far these are the latest outputs for huntsman and stockfish, respectively:

So huntsman has finally found the mate in 25. :) Complete logs attached, with the following mating line being given:
```
```

**Comment by robertnurnberg** [comment]
So I guess it makes sense to open a PR and address the two issues reported in the original post. What filename would you like to settle on? @vondele 
Something like `ChestUCI_20230525.epd` to mark the date the new best mate was found, or a stable name like `ChestUCI_matetrack.epd` from now on?

**Comment by vondele** [comment]
Maybe just matetrack.epd ?
