### ISSUE TITLE
Feature request: output total time and nodes

### ISSUE THREAD

**Issue by joergoster** [vondele/matetrack#98]
Is it possible to also output the total number of nodes searched? The same for total time used. Maybe similar to what SF's bench does.

This should help in evaluating how much effort an engine has put into the specified task compared to other engines. For example, how close to the nodes limit it stays, or if it grossly oversteps or stays below that limit.

**Comment by robertnurnberg** [comment]
Master has some stats on nodes (and depth) when the options `--mate` or `--showAllStats` are used. (see below)

Adding total nodes searched and time used could be added as well, but here I would like to hear from maintainer first, before adding it. At the moment the nodes searched statistics only count the last exact score info output, so in any case it may not be exactly what you are looking for?

```
> python matecheck.py --epdFile mates2000.epd --mate 0 --nodes "10**6"
Loaded 2000 FENs, with max(abs(bm)) = 27.

Matetrack started for ./stockfish on mates2000.epd with --nodes 1000000 --mate 0 ...
100%|#########################################| 100/100 [01:43<00:00,  1.04s/it]


Using ./stockfish on mates2000.epd with --nodes 1000000 --mate 0
Engine ID:     Stockfish dev-20240623-cc992e5e
Total FENs:    2000
Found mates:   1810
Best mates:    1714

Best mate statistics:
abs(bm) = 1 - mates: 6, nodes (min avg max): 77 208 588, depth (min avg max): 1 4 7
abs(bm) = 2 - mates: 12, nodes (min avg max): 21 19427 181977, depth (min avg max): 5 14 41
abs(bm) = 3 - mates: 29, nodes (min avg max): 236 47569 846951, depth (min avg max): 8 18 28
abs(bm) = 4 - mates: 62, nodes (min avg max): 596 108783 968011, depth (min avg max): 6 21 41
abs(bm) = 5 - mates: 115, nodes (min avg max): 834 166166 935975, depth (min avg max): 8 24 52
abs(bm) = 6 - mates: 361, nodes (min avg max): 152 168251 1000482, depth (min avg max): 7 24 71
abs(bm) = 7 - mates: 413, nodes (min avg max): 232 176004 988360, depth (min avg max): 6 25 71
abs(bm) = 8 - mates: 206, nodes (min avg max): 629 164848 887995, depth (min avg max): 10 27 62
abs(bm) = 9 - mates: 155, nodes (min avg max): 287 186419 988866, depth (min avg max): 1 25 61
abs(bm) = 10 - mates: 91, nodes (min avg max): 2212 176647 926642, depth (min avg max): 1 24 42
abs(bm) = 11 - mates: 68, nodes (min avg max): 1419 229889 971417, depth (min avg max): 11 27 53
abs(bm) = 12 - mates: 59, nodes (min avg max): 1604 180013 888999, depth (min avg max): 13 27 52
abs(bm) = 13 - mates: 37, nodes (min avg max): 6318 194581 789161, depth (min avg max): 12 26 46
abs(bm) = 14 - mates: 33, nodes (min avg max): 14813 254886 949973, depth (min avg max): 13 29 48
abs(bm) = 15 - mates: 23, nodes (min avg max): 18534 186509 898470, depth (min avg max): 12 28 47
abs(bm) = 16 - mates: 8, nodes (min avg max): 108957 302745 626218, depth (min avg max): 24 32 41
abs(bm) = 17 - mates: 10, nodes (min avg max): 37319 353164 907190, depth (min avg max): 20 33 47
abs(bm) = 18 - mates: 7, nodes (min avg max): 25003 381431 986754, depth (min avg max): 15 34 68
abs(bm) = 19 - mates: 5, nodes (min avg max): 12690 136602 336200, depth (min avg max): 30 40 63
abs(bm) = 20 - mates: 8, nodes (min avg max): 13652 296096 783396, depth (min avg max): 15 35 58
abs(bm) = 21 - mates: 2, nodes (min avg max): 4982 6264 7545, depth (min avg max): 12 14 16
abs(bm) = 22 - mates: 2, nodes (min avg max): 97062 394692 692322, depth (min avg max): 23 46 70
abs(bm) = 24 - mates: 1, nodes (min avg max): 497122 497122 497122, depth (min avg max): 47 47 47
abs(bm) = 25 - mates: 1, nodes (min avg max): 175337 175337 175337, depth (min avg max): 47 47 47
```

**Comment by vondele** [comment]
I'm fine with other summary statistics, as part of --showAllStats, as long as they are meaningful and somewhat concise. Probably adding to the above the non-mates would already add some useful info ? Feel free to add.

**Comment by robertnurnberg** [comment]
I am thinking of adding an option `--bench` with output style same as `./stockfish bench`, i.e.:
```
===========================
Total time (ms) : 1634
Nodes searched  : 1038234
Nodes/second    : 635394
```

This would be final output of the script, in addition to what it currently prints.

But note that here `Nodes searched` would only count those leading up to the latest exact score output by the engine. This is because our script ignores any lower/upper bound info lines, and I would like to keep these counts consisent with that. Would that be OK with both of you? (thumbs up suffices)

In any case, I am going to wait with that until currently open PR is merged or closed, as this new feature will somewhat overlap with changes in there.

**Comment by joergoster** [comment]
> Master has some stats on nodes (and depth) when the options --mate or --showAllStats are used. (see below)

That's definitely some useful stats, too!

**Comment by joergoster** [comment]
I would prefer to simply have the total number of nodes searched. However, since The Huntsman only outputs lower- or upperbound scores as the last info line under very rare circumstances, if ever, this will probably work for me, as well.
